
# Base Path config
log_name: knee_cart_degree_under_image
log_path: ./log/
data_path: ../Dataset/
list_path: ../Dataset/Cart_Degree_split.csv

# Mask Config
mask_type: vds
kspace_size: [640,400]
recon_size: [320,320]
center_fractions: [0.00]

#Data Config
batch_size: 16
sample_rate: 1.0
test_path:
num_classes: 2 #each label is binary task
num_label: 1 #labels in total
class_list:
label_names: Full
thresh: [0.5]

# Network Config
model_type: resnet50
fine_tune: False
loss_type: WCE
in_channel: 2
mode: test
max_epochs: 200
num_gpus: 1
num_workers: 4
lr: 0.00005
lr_step_size: 40
lr_gamma: 0.1
weight_decay: 0.0001
dropout_prob: 0.5
feature_map_input_layer: 2
thresh_method: None

# resume train
monitor: val_Full/roc_auc
pretrained_model_checkpoint:
resume_train: False
ckpt_path:

